import "~/styles/globals.css";

import { Krona_One } from "next/font/google";
import { type Metadata } from "next";
const inter = Krona_One({
  subsets: ["latin"],
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>{children}</body>
    </html>
  );
}
